"""
Azure Architecture Diagram: Rebel Tactical Platform
Generated by diagram-generator agent
Date: 2026-01-19

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt install graphviz)

Generate PNG: python 03-des-diagram.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.web import AppServices
from diagrams.azure.compute import FunctionApps
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.network import CDNProfiles
from diagrams.azure.general import Resourcegroups
from diagrams.onprem.client import Users

# Diagram configuration
graph_attr = {
    "fontsize": "28",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
    "nodesep": "0.8",
    "ranksep": "1.0"
}

node_attr = {
    "fontsize": "12"
}

edge_attr = {
    "fontsize": "10"
}

with Diagram(
    "Rebel Tactical Platform - Azure Architecture",
    show=False,
    direction="TB",
    filename="03-des-diagram",
    outformat="png",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr
):
    # External users
    rebels = Users("Rebel Operatives\n(Browser)")

    with Cluster("Azure Cloud - West Europe"):

        with Cluster("Resource Group: rg-rebel-tactical-prod-weu"):

            # Azure Static Web Apps with CDN
            with Cluster("Azure Static Web Apps (Standard)"):
                cdn = CDNProfiles("Global CDN\nEdge Locations")

                with Cluster("Frontend"):
                    frontend = AppServices(
                        "React SPA\n• 3D Death Star\n• Mission Board\n• Intel Feed")

                with Cluster("Managed Functions Runtime"):
                    api_missions = FunctionApps("GET /api/missions")
                    api_intel = FunctionApps("GET /api/intelligence")
                    api_reports = FunctionApps("POST /api/reports")

            # Observability Stack
            with Cluster("Observability"):
                app_insights = ApplicationInsights(
                    "Application Insights\nappi-rebel-tactical-prod-weu")
                log_analytics = LogAnalyticsWorkspaces(
                    "Log Analytics\nlog-rebel-tactical-prod-weu")

    # Data Flow - User requests
    rebels >> Edge(label="HTTPS", color="darkgreen", style="bold") >> cdn
    cdn >> Edge(label="Static Assets", color="blue") >> frontend

    # Frontend to API calls
    frontend >> Edge(label="API Calls", color="orange",
                     style="dashed") >> api_missions
    frontend >> Edge(label="", color="orange", style="dashed") >> api_intel
    frontend >> Edge(label="", color="orange", style="dashed") >> api_reports

    # Telemetry flow
    frontend >> Edge(label="Telemetry", color="purple",
                     style="dotted") >> app_insights
    api_missions >> Edge(label="", color="purple",
                         style="dotted") >> app_insights
    api_intel >> Edge(label="", color="purple", style="dotted") >> app_insights
    api_reports >> Edge(label="", color="purple",
                        style="dotted") >> app_insights

    # Logs flow
    app_insights >> Edge(label="Logs", color="gray") >> log_analytics
