"""
Azure Architecture Diagram: Rebel Tactical Platform (AS-BUILT)
Generated by workload-documentation-generator agent
Date: 2026-01-20

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt install graphviz)

Generate PNG: python 07-ab-diagram.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.web import AppServices
from diagrams.azure.compute import FunctionApps
from diagrams.azure.devops import ApplicationInsights
from diagrams.azure.analytics import LogAnalyticsWorkspaces
from diagrams.azure.network import CDNProfiles
from diagrams.azure.general import Resourcegroups
from diagrams.onprem.client import Users

# Diagram configuration
graph_attr = {
    "fontsize": "28",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "ortho",
    "nodesep": "0.8",
    "ranksep": "1.0"
}

node_attr = {
    "fontsize": "12"
}

edge_attr = {
    "fontsize": "10"
}

with Diagram(
    "Rebel Tactical Platform - AS-BUILT Architecture",
    show=False,
    direction="TB",
    filename="07-ab-diagram",
    outformat="png",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr
):
    # External users
    users = Users("Death Star\nPersonnel\n(External)")

    # Azure Subscription boundary
    with Cluster("Azure Subscription: noalz\n00858ffc-dded-4f0f-8bbf-e17fff0d47d9"):

        # Resource Group
        with Cluster("Resource Group: rg-rebel-tactical-prod-weu\nRegion: West Europe"):

            # Static Web App with integrated Functions
            with Cluster("Azure Static Web Apps - Standard Tier\nstapp-rebel-tactical-prod-weu\n$9.00/month"):
                swa = AppServices(
                    "React SPA\n(Vite + React 18)\nDomain: icy-rock-0fd499b03.4")

                with Cluster("Managed Azure Functions\nNode.js 18 Runtime\nIncluded in SWA"):
                    func_intel = FunctionApps(
                        "GetIntelligence\nHTTP GET\n~0.8s latency")
                    func_missions = FunctionApps(
                        "GetMissions\nHTTP GET\n~0.8s latency")
                    func_reports = FunctionApps(
                        "SubmitReport\nHTTP POST\n~3.2s latency")

            # CDN (implicit, included in SWA)
            cdn = CDNProfiles(
                "Azure CDN\n(Global Edge Locations)\nIncluded in SWA Standard")

            # Monitoring & Observability
            with Cluster("Monitoring & Observability\n$8.30/month combined"):
                appi = ApplicationInsights(
                    "Application Insights\nappi-rebel-tactical-prod-weu\nWorkspace-based\n$5.44/month")
                log = LogAnalyticsWorkspaces(
                    "Log Analytics\nlog-rebel-tactical-prod-weu\n391cfd44-e196-4674\n30-day retention\n$2.86/month")

    # Traffic flow
    users >> Edge(label="HTTPS\nTTFB: 1.1s") >> cdn
    cdn >> Edge(label="Static assets\n(React SPA)") >> swa
    swa >> Edge(label="API calls") >> func_intel
    swa >> Edge(label="API calls") >> func_missions
    swa >> Edge(label="API calls") >> func_reports

    # Telemetry flow
    func_intel >> Edge(label="Traces, metrics\n193 traces/day",
                       style="dashed", color="blue") >> appi
    func_missions >> Edge(label="Perf counters\n171/day",
                          style="dashed", color="blue") >> appi
    func_reports >> Edge(label="Requests\n7/day",
                         style="dashed", color="blue") >> appi
    appi >> Edge(label="Centralized logs\n~2.2GB/month",
                 style="dashed", color="green") >> log

print("✅ As-built architecture diagram generated: 07-ab-diagram.png")
print("\nKey differences from design phase:")
print("- Static Web App deployed (not App Service)")
print("- Managed Functions used (no separate Function App)")
print("- Workspace-based Application Insights (centralized)")
print("- 30-day retention configured (Log Analytics)")
print("- West Europe region (GDPR compliance)")
print("\nActual costs: $17.24/month")
print("Budget utilization: 86.2% of $20 budget")
print("Status: ✅ All resources healthy, 100% availability")
